TRI_LAYER_ENABLE = yes

# AVR optimisations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
# (we use these currently)
# EXTRAKEY_ENABLE = no
# MAGIC_ENABLE = no
