notARepository: 'quit'
git:
  overrideGpg: true
  disableForcePushing: true
os:
  editPreset: nvim
gui:
  showBranchCommitHash: true
keybinding:
  universal:
    scrollUpMain-alt2: <c-p>
    scrollDownMain-alt2: <c-n>
    executeShellCommand: ';'
