return {
  "https://gitlab.com/Biggybi/nvim-smartcd.git",
  event = { "BufEnter" },
  lazy = false,
  opts = {
    create_keymaps = true,
    markers = {
      ".git",
      ".svn",
      ".github",
      "Justfile",
    },
    ft_markers = {
      javascript = {
        "package.json",
        "yarn.lock",
        ".eslintrc.json",
        ".prettierrc",
        ".prettierrc.json",
        ".prettierrc.yaml",
        ".prettierrc.toml",
        "node_modules",
      },
      typescript = {
        "package.json",
        "yarn.lock",
        ".eslintrc.json",
        ".prettierrc",
        ".prettierrc.json",
        ".prettierrc.yaml",
        ".prettierrc.toml",
        "node_modules",
      },
      lua = { ".luacheckrc", ".luastyle", ".stylua.toml", "stylua.toml" },
      rust = { "Cargo.toml", "Cargo.lock" },
      python = { "Pipfile" },
      c = { "Makefile" },
      cpp = { "Makefile" },
      zig = { "build.zig" },
    },
  },
  cmd = { "SmartCd" },
  keys = require("keymaps").smartcd,
}
