[manager]
append_keymap = [
    { on = [ "q" ], run = "close", desc = "Close the current tab, or quit if it is last tab" },
    { on = [ "n" ], run = "create", desc = "Create a file or directory (ends with / for directories)" },
]

prepend_keymap = [
    { on = ["g","m"], run = "cd ~/Music",     desc = "~/Music" },
    { on = ["g","d"], run = "cd ~/Downloads", desc = "~/Downloads" },
    { on = ["g","t"], run = "cd ~/Torrents",  desc = "~/Torrents" },
    { on = ["g","h"], run = "cd ~/",          desc = "~/" },
    { on = ["g","b"], run = "cd ~/Books",     desc = "~/Books" },
    { on = ["g","p"], run = "cd ~/Projects/", desc = "~/Projects" },
    { on = ["g","n"], run = "cd ~/Notes/",    desc = "~/Notes" },
    # These are all for plugins
    { on = ["T"],     run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
    { on = ["c","a"], run = "plugin compare",            desc = "Archive selected files" },
    { on = ["c","x"], run = "chmod+x",                   desc = "Archive selected files" },
    ## glow.yazi
    { on = ["<C-p>"], run = "seek -5",        desc = "Scroll up the markdown preview" },
    { on = ["<C-n>"], run = "seek 5",         desc = "Scroll down the markdown preview" },
    # eza-preview
    { on = ["E"],     run = "plugin eza-preview",                        desc = "Toggle tree/list dir preview" },
    { on = ["-"],     run = "plugin eza-preview inc-level",              desc = "Increment tree level" },
    { on = ["_"],     run = "plugin eza-preview dec-level",              desc = "Decrement tree level" },
    { on = ["$"],     run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },
]


