[manager]
append_keymap = [
    { on = [ "q" ], run = "close", desc = "Close the current tab, or quit if it is last tab" },
]

prepend_keymap = [
    { on = ["g","b"], run = "cd ~/Books",     desc = "~/Books" },
    { on = ["g","c"], run = "cd ~/.config",     desc = "~/.config" },
    { on = ["g","C"], run = "cd ~/.local/share/chezmoi",     desc = "~/.config (chezmoi)" },
    { on = ["g","d"], run = "cd ~/Downloads", desc = "~/Downloads" },
    { on = ["g","h"], run = "cd ~/",          desc = "~/" },
    { on = ["g","m"], run = "cd ~/Music",     desc = "~/Music" },
    { on = ["g","n"], run = "cd ~/Notes/",    desc = "~/Notes" },
    { on = ["g","p"], run = "cd ~/Projects/", desc = "~/Projects" },
    { on = ["g","t"], run = "cd ~/Torrents",  desc = "~/Torrents" },
    { on = ["<C-p>"], run = "seek -5",        desc = "Scroll up the markdown preview" },
    { on = ["<C-n>"], run = "seek 5",         desc = "Scroll down the markdown preview" },

    # PLUGINS
    { on = ["T"],     run = "plugin toggle-pane min-preview", desc = "Toggle hiding preview pane" },
    { on = ["F"],     run = "plugin toggle-pane max-current", desc = "Toggle maximising current pane" },
    { on = ["c", "a"],run = "plugin archive", desc = "Archive file" },
    # eza-preview
    { on = ["E"],     run = "plugin eza-preview",                        desc = "Toggle tree/list dir preview" },
    { on = ["-"],     run = "plugin eza-preview inc-level",              desc = "Increment tree level" },
    { on = ["_"],     run = "plugin eza-preview dec-level",              desc = "Decrement tree level" },
    { on = ["$"],     run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },
]
