# https://yazi-rs.github.io/docs/configuration/yazi/
[mgr]
ratio          = [ 1, 3, 4 ]
sort_by        = "natural"
sort_dir_first = true
linemode       = "size_and_mtime"
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 4
max_width       = 2000
max_height      = 2000
# cache_dir       = ""
image_delay     = 40
# image_filter    = "triangle"
# image_quality   = 50
# sixel_fraction  = 15

# also see https://yazi-rs.github.io/docs/configuration/yazi#open
# [opener]
# play = [
#     { run = 'mpv "$@"', orphan = true, for = "unix" },
#     { run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
# ]
# edit = [
#     { run = '$EDITOR "$@"', block = true, for = "unix" },
#     { run = "%EDITOR% %*",  block = true, for = "windows" },
# ]
# open = [
#     { run = 'xdg-open "$@"', desc = "Open" },
# ]

[log]
enabled = false

[plugin]
prepend_previewers = [
    # { mime = "{image,audio,video}/*", run = "mediainfo"},
    # { mime = "application/subrip", run = "mediainfo"},
    { mime = "application/epub+zip", run = "archive"},
    { name = "*.jar", run = "archive"},
    { name = "*.war", run = "archive"},
    # { name = "*.md", run = "glow" },
    # { name = "*/", run = "eza-preview" }
]


append_previewers = [
    # { name = "*", run = "hexyl" }
]
